#!/bin/bash

Ip=$(echo `az vm list-ip-addresses -g ansiblerg1 -n Ansiblevm --query "[].virtualMachine.network.publicIpAddresses[*].ipAddress" -o tsv`)


echo "[linux]" >> /etc/ansible/hosts
echo "$Ip" >> /etc/ansible/hosts
echo "[linux:vars]" >> /etc/ansible/hosts
echo "ansible_ssh_user = vmadmin" >> /etc/ansible/hosts
echo "ansible_ssh_pass = Sambhavjain123" >> /etc/ansible/hosts
